## Plotting emissions by sector

Using NYC data downloaded from the Mayor's Office of Climate & Environmental Justice 

Light cleaning and plotting using Altair:

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("./raw data/consumption_2021.csv")

In [12]:
df

,Main Sector,Source,Source_category,Units,FY 2021 Consumed,FY 2021 tCO2e,FY 2021 Source MMBtu
0,Buildings,#1 fuel oil,Other,liter,0.00,0.00,0.00
1,Buildings,#2 fuel oil,#2 fuel oil,liter,"40,000,493.01","108,765.96","1,476,133.54"
2,Buildings,#4 fuel oil,#4 fuel oil,liter,"43,738,271.41","127,460.25","1,704,649.56"
3,Buildings,#6 fuel oil,#6 fuel oil,liter,0.00,0.00,0.00
4,Buildings,Biodiesel,Other,liter,"5,709,254.47",63.18,"194,936.16"
5,Buildings,Electricity,Electricity,kWh,"2,729,478,210.72","985,555.63","9,312,979.65"
6,Buildings,Kerosene,Other,liter,0.00,0.00,0.00
7,Buildings,Natural gas,Natural gas,GJ,"13,535,870.57","682,475.30","13,471,004.47"
8,Buildings,Propane,Other,liter,"100,455.75",149.77,"2,441.02"
9,Buildings,Steam,Steam,kg,"675,839,670.63","56,828.11",0.00
10,Transportation,Gasoline,Gasoline,liter,"35,861,921.67","84,813.89","1,196,056.76"
11,Transportation,Ethanol,Other,liter,"3,942,609.98",412.41,"88,920.71"
12,Transportation,Diesel - trucks,Diesel,liter,"54,362,383.67","145,839.31","2,011,654.30"
13,Transportation,Biodiesel,Other,liter,"6,249,783.54",7.23,"213,391.92"
14,Transportation,Diesel - marine vessels,Diesel,liter,"20,584,142.65","56,279.90","759,614.22"
15,Transportation,Electricity,Electricity,kWh,"884,293.22",319.30,"3,017.21"
16,Transportation,Jet fuel,Other,liter,"929,061.62","2,412.84","33,464.67"
17,Streetlights and Traffic Signals,Electricity,Electricity,kWh,"147,793,221.38","53,364.94","504,270.47"
18,Wastewater Treatment,#1 fuel oil,Other,liter,0.00,0.00,0.00
19,Wastewater Treatment,#2 fuel oil,#2 fuel oil,liter,"8,250,840.29","22,372.65","304,479.80"
20,Wastewater Treatment,#4 fuel oil,#4 fuel oil,liter,0.00,0.00,0.00
21,Wastewater Treatment,#6 fuel oil,#6 fuel oil,liter,0.00,0.00,0.00
22,Wastewater Treatment,Biodiesel,Other,liter,"434,254.75",4.81,"14,827.15"
23,Wastewater Treatment,Electricity,Electricity,kWh,"683,214,586.23","246,694.03","2,331,128.17"
24,Wastewater Treatment,Natural gas,Natural gas,GJ,"493,316.66","24,817.65","490,952.61"
25,Wastewater Treatment,Propane,Other,liter,"151,783.66",226.30,"3,688.27"
26,Wastewater Treatment,Kerosene,Other,liter,0.00,0.00,0.00
27,Wastewater Treatment,Steam,Steam,kg,"24,459,023.27","2,056.64",0.00
28,Wastewater Treatment,CH4,Fugitive CH4,MT,"1,410.94","39,506.39",0.00
29,Wastewater Treatment,N2O,Fugitive CH4,MT,212.73,"56,374.50",0.00
30,Water Supply,#1 fuel oil,Other,liter,0.00,0.00,0.00
31,Water Supply,#2 fuel oil,#2 fuel oil,liter,"12,757.97",34.69,470.81
32,Water Supply,#4 fuel oil,#4 fuel oil,liter,0.00,0.00,0.00
33,Water Supply,#6 fuel oil,#6 fuel oil,liter,0.00,0.00,0.00
34,Water Supply,Biodiesel,Other,liter,634.06,0.00,21.65
35,Water Supply,Electricity,Electricity,kWh,"104,088,577.66","37,584.14","355,150.23"
36,Water Supply,Natural gas,Natural gas,GJ,"174,841.48","8,795.88","174,003.61"
37,Water Supply,Kerosene,Other,liter,0.00,0.00,0.00
38,Water Supply,Propane,Other,liter,"4,365,484.75","6,508.70","106,079.06"
39,Water Supply,Steam,Steam,kg,0.00,0.00,0.00
40,Solid Waste Facilities,CH4,Fugitive CH4,MT,"43,136.11","111,371.30",0.00
41,Fugitive and Process Emissions,Other,Other,kg,"9,386.50","13,314.18",0.00
42,Total,Total,Total,Total,4604709891.35,2874409.88,34753336.02

In [17]:
df['FY 2021 tCO2e'] = df['FY 2021 tCO2e'].str.replace(",", "")

In [18]:
df['FY 2021 tCO2e'] = df['FY 2021 tCO2e'].astype(float)

In [19]:
grouped = df.groupby('Main Sector')['FY 2021 tCO2e'].sum().reset_index()

In [20]:
grouped

                        Main Sector  FY 2021 tCO2e
0                         Buildings     1961298.20
1    Fugitive and Process Emissions       13314.18
2            Solid Waste Facilities      111371.30
3  Streetlights and Traffic Signals       53364.94
4                             Total     2874409.88
5                    Transportation      290084.88
6              Wastewater Treatment      392052.97
7                      Water Supply       52923.41

In [26]:
grouped = grouped[grouped['Main Sector'] != 'Total']

In [27]:
grouped

                        Main Sector  FY 2021 tCO2e
0                         Buildings     1961298.20
1    Fugitive and Process Emissions       13314.18
2            Solid Waste Facilities      111371.30
3  Streetlights and Traffic Signals       53364.94
5                    Transportation      290084.88
6              Wastewater Treatment      392052.97
7                      Water Supply       52923.41

In [32]:
grouped = grouped.sort_values(by='FY 2021 tCO2e', ascending=False)

In [35]:
grouped["percent"] = grouped["FY 2021 tCO2e"] * 100 / grouped["FY 2021 tCO2e"].sum()

In [36]:
grouped

                        Main Sector  FY 2021 tCO2e    percent
0                         Buildings     1961298.20  68.233073
6              Wastewater Treatment      392052.97  13.639425
5                    Transportation      290084.88  10.091980
2            Solid Waste Facilities      111371.30   3.874580
3  Streetlights and Traffic Signals       53364.94   1.856553
7                      Water Supply       52923.41   1.841192
1    Fugitive and Process Emissions       13314.18   0.463197

This shows me the percentage of energy consumption that each sector is responsible for. Needed to verify the "buildings account for 70 percent of the city's emissions" statement.

In [39]:
import altair as alt

# make a bar chart of FY 2021 tCO2e

alt.Chart(grouped).mark_bar().encode(
    y=alt.Y('Main Sector', sort='-x'),
   x='FY 2021 tCO2e',
    
)

alt.Chart(...)

Chart to download and edit in Illustrator.